{{- if and .Values.maple.ingestKey.value (not .Values.maple.ingestKey.existingSecret.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maple-k8s-infra.ingestSecretName" . }}
  labels:
    {{- include "maple-k8s-infra.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "maple-k8s-infra.ingestSecretKey" . }}: {{ .Values.maple.ingestKey.value | quote }}
{{- end -}}
