/**
 * Project chat-flue's Worker vars out of the repo-root `.env.local` into
 * `apps/chat-flue/.dev.vars`.
 *
 * Why a script rather than a flag: on the Cloudflare target `flue dev` hands the
 * Worker to `@cloudflare/vite-plugin`, and Worker vars come from `.dev.vars` next
 * to the generated wrangler config (the Cloudflare convention). `flue dev --env
 * <path>` does NOT reach them — the CLI restores the env file before starting the
 * dev server, so it only affects config resolution. Every other Worker in this
 * repo reads `.env.local` via `wrangler dev --env-file`; this keeps chat-flue on
 * the same single source instead of a second copy of the same secrets.
 *
 * Deliberately a whitelist: `--env-file` hands a Worker *every* key in the file
 * (R2, Tinybird, the GitHub app private key), and that shouldn't spread here.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { parseEnv } from "node:util"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const SOURCE = join(ROOT, ".env.local")
const TARGET = join(ROOT, "apps/chat-flue/.dev.vars")

/** The keys `ChatFlueEnv` actually reads (apps/chat-flue/src/lib/env.ts). */
const PROJECTED = [
	"INTERNAL_SERVICE_TOKEN",
	"MAPLE_AUTH_MODE",
	"CLERK_SECRET_KEY",
	"CLERK_PUBLISHABLE_KEY",
	"CLERK_JWT_KEY",
	"MAPLE_ROOT_PASSWORD",
	"MAPLE_ORG_ID_OVERRIDE",
	"MAPLE_INGEST_KEY",
	"MAPLE_ENDPOINT",
	"MAPLE_ENVIRONMENT",
] as const

const HEADER =
	"# GENERATED by scripts/sync-chat-flue-dev-vars.ts from .env.local — edits above the marker are overwritten."
const MARKER = "# --- local overrides below this line are preserved ---"

const source: Record<string, string | undefined> = existsSync(SOURCE)
	? parseEnv(readFileSync(SOURCE, "utf-8"))
	: {}

// Without these, `/agents/*` rejects every browser request with a bare 401 and no
// hint as to why — the single most common local-dev dead end for the chat.
if (!source.INTERNAL_SERVICE_TOKEN) {
	console.error("[chat-flue] .env.local has no INTERNAL_SERVICE_TOKEN — apps/api cannot start a turn.")
}
if (source.MAPLE_AUTH_MODE?.toLowerCase() === "clerk" && !source.CLERK_SECRET_KEY) {
	console.error("[chat-flue] MAPLE_AUTH_MODE=clerk but CLERK_SECRET_KEY is unset — /agents/* will 401.")
} else if (!source.MAPLE_AUTH_MODE) {
	console.error("[chat-flue] .env.local has no MAPLE_AUTH_MODE — chat-flue and the web app may disagree.")
}

const previous = existsSync(TARGET) ? readFileSync(TARGET, "utf-8") : ""
const preserved = previous.includes(MARKER) ? (previous.split(MARKER)[1]?.trim() ?? "") : ""

const lines = [HEADER, ""]
for (const key of PROJECTED) {
	const value = source[key]
	if (value) lines.push(`${key}=${JSON.stringify(value)}`)
}
lines.push("", MARKER, preserved, "")

writeFileSync(TARGET, lines.join("\n"))
