import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const currentDir = dirname(fileURLToPath(import.meta.url))
const drizzleDir = resolve(currentDir, "../drizzle")
const defaultOutFile = resolve(currentDir, "../.generated/d1-migrations.sql")

const outArgIndex = process.argv.findIndex((arg) => arg === "--out")
const outFile =
  outArgIndex >= 0 && process.argv[outArgIndex + 1]
    ? resolve(process.cwd(), process.argv[outArgIndex + 1]!)
    : defaultOutFile

const migrationFiles = readdirSync(drizzleDir)
  .filter((entry) => entry.endsWith(".sql"))
  .sort()

const statements = migrationFiles.map((fileName) => {
  const contents = readFileSync(resolve(drizzleDir, fileName), "utf8").trim()
  return `-- ${fileName}\n${contents}`
})

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(
  outFile,
  [
    "-- Generated by packages/db/scripts/create-d1-migration-bundle.ts",
    "PRAGMA foreign_keys = OFF;",
    ...statements,
    "PRAGMA foreign_keys = ON;",
    "",
  ].join("\n\n"),
)

console.log(outFile)
