#!/bin/sh
# Xcode Cloud runs this immediately after cloning, before it resolves the
# project. It has to exist because three things Xcode Cloud needs are
# deliberately gitignored:
#
#   Maple.xcodeproj          generated by XcodeGen (.pbxproj is merge-hostile)
#   Maple/Resources/Info.plist   generated from project.yml's `info:` block
#   Config/Secrets.xcconfig  real keys
#
# Without this the build fails at "no such project", not at a compile error —
# so if a workflow dies before the first log line, look here first.
set -eu

cd "$CI_PRIMARY_REPOSITORY_PATH/apps/ios"

# Xcode Cloud images ship Homebrew but not XcodeGen.
brew install xcodegen

# The publishable key is a build input, not a secret in the confidentiality
# sense — the web app ships the same class of value in its JS bundle — but it
# still picks prod vs test, so it comes from the workflow's environment rather
# than source. Set CLERK_PUBLISHABLE_KEY in App Store Connect → Xcode Cloud →
# your workflow → Environment. Use the `pk_live_…` key: a `pk_test_` session is
# rejected by api.maple.dev, which is what a TestFlight build talks to.
if [ -z "${CLERK_PUBLISHABLE_KEY:-}" ]; then
	echo "CLERK_PUBLISHABLE_KEY is not set on this workflow." >&2
	echo "Add it under Xcode Cloud → Workflow → Environment, then re-run." >&2
	exit 1
fi

# DEVELOPMENT_TEAM is deliberately absent: Xcode Cloud manages signing itself,
# and an explicit team here fights its cloud-managed certificates.
cat >Config/Secrets.xcconfig <<EOF
CLERK_PUBLISHABLE_KEY = $CLERK_PUBLISHABLE_KEY
EOF

xcodegen generate
